name: work

on:
  push:
    branches:
      - master
      - release
  pull_request:
    branches:
      - master
      - release
      - develop
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FULL_NAME: "Нетупский Пётр Юрьевич"
      GROUP_NUMBER: "M3115"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print Info
        run: echo "ФИО:${{ env.FULL_NAME }}, Группа:${{ env.GROUP_NUMBER }}, GitHub:${{ github.actor }}"
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: pip freeze
        run: pip freeze > requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run unit tests
        run: pytest
      - name: Install black
        run: pip install black
      - name: Code Style Check
        run: flake8 .
      - name: Format Code
        run: black . --line-length 120 
